version: '3.8'

services:
  frontend:
    build:
      context: ./chatbot-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=api.py
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - http_proxy=
      - https_proxy=
      - HTTP_PROXY=
      - HTTPS_PROXY=
    volumes:
      - ./.env:/app/.env
      - ./.spotify_caches:/app/.spotify_caches:rw
      - ~/Desktop:/host/Desktop:rw
      - ~/Documents:/host/Documents:rw
      - ~/Downloads:/host/Downloads:rw
      - ~/Pictures:/host/Pictures:rw
      - ~/Music:/host/Music:rw
      - ~/Videos:/host/Videos:rw
    privileged: true
    # Use environment variables for user and group IDs
    # To set these, run: export DOCKER_USER_ID=$(id -u) && export DOCKER_GROUP_ID=$(id -g)
    user: "${DOCKER_USER_ID:-1000}:${DOCKER_GROUP_ID:-1000}" 